[package]
name = "tt-health-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
influxdb = { version = "0.7.2", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
